[project]
name = "panoseti_ctapipe_plugin"
version = "0.1.0"
description = "PANOSETI ctapipe plugin"
authors = [{name = "Sruthiranjani Ravikularaman", email = "sruthi@astro.rub.de"}]
dependencies = [
	"ctapipe",
	"numpy",
	"astropy",
	"pypff",
	"pandas",
]

[build-system]
requires = ["setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
	"panoseti_ctapipe_plugin",
	"panoseti_ctapipe_plugin.plugin_src",
	"panoseti_ctapipe_plugin.utils",
]
include-package-data = true

[tool.setuptools.package-dir]
panoseti_ctapipe_plugin = "."

[tool.setuptools.package-data]
panoseti_ctapipe_plugin = ["default_data/*.csv"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[project.entry-points.ctapipe_io]
PanoEventSource = "panoseti_ctapipe_plugin:PanoEventSource"